using System;

namespace BejeweledLivePlus
{
	public enum Badges
	{
		BADGE_LEVELORD,
		BADGE_BEJGOLD,
		BADGE_BRONZE,
		BADGE_PLATINUM,
		BADGE_RELICSILVER,
		BADGE_RELICPLATINUM,
		BADGE_FINALFRENZYBRONZE,
		BADGE_FINALFRENZYPLATINUM,
		BADGE_HIGHVOLATAGEBRONZE,
		BADGE_HIGHVOLATAGEPLATINUM,
		BADGE_MONARCHSILVER,
		BADGE_MONARCHPLATINUM,
		BADGE_BONANZABRONZE,
		BADGE_BONANZAPLATINUM,
		BADGE_CHROMATICGOLD,
		BADGE_STELLARGOLD,
		BADGE_BLASTERGOLD,
		BADGE_SUPERSTAR,
		BADGE_CHAINREACTIONGOLD,
		BADGE_LUCKYSTREAKGOLD,
		NUM_BADGES
	}
}
