using System;

namespace BejeweledLivePlus
{
	public enum InterfaceState
	{
		INTERFACE_STATE_LOADING,
		INTERFACE_STATE_MAINMENU,
		INTERFACE_STATE_OPTIONSMENU,
		INTERFACE_STATE_GAMEDETAILMENU,
		INTERFACE_STATE_BADGEMENU,
		INTERFACE_STATE_PROFILEMENU,
		INTERFACE_STATE_STATSMENU,
		INTERFACE_STATE_HIGHSCORESMENU,
		INTERFACE_STATE_EDITPROFILEMENU,
		INTERFACE_STATE_CREDITSMENU,
		INTERFACE_STATE_ABOUTMENU,
		INTERFACE_STATE_LEGALMENU,
		INTERFACE_STATE_PAUSEMENU,
		INTERFACE_STATE_ZENOPTIONSMENU,
		INTERFACE_STATE_HELPMENU,
		INTERFACE_STATE_HELPANDOPTIONSMENU,
		INTERFACE_STATE_INGAME,
		NUM_INTERFACE_STATES
	}
}
