using System;

namespace BejeweledLivePlus
{
	public enum Menu_Type
	{
		MENU_BACKGROUND,
		MENU_GAMEBOARD,
		MENU_MAINMENU,
		MENU_FADE_UNDERLAY,
		MENU_MOREGAMESMENU,
		MENU_MAINMENUOPTIONSMENU,
		MENU_GAMEDETAILMENU,
		MENU_PAUSEMENU,
		MENU_HELPMENU,
		MENU_OPTIONSMENU,
		MENU_HELPANDOPTIONSMENU,
		MENU_BADGEMENU,
		MENU_PROFILEMENU,
		MENU_STATSMENU,
		MENU_HIGHSCORESMENU,
		MENU_EDITPROFILEMENU,
		MENU_CREDITSMENU,
		MENU_ABOUTMENU,
		MENU_LEGALMENU,
		MENU_ZENOPTIONSMENU,
		NUM_MENUS
	}
}
