using System;

namespace BejeweledLivePlus
{
	public enum TutorialsEnum
	{
		TUTORIAL_BASICS,
		TUTORIAL_FLAME,
		TUTORIAL_LASER,
		TUTORIAL_HYPERCUBE,
		TUTORIAL_MULTIPLIER,
		TUTORIAL_OTHER_MODE,
		TUTORIAL_SUPERNOVA,
		TUTORIAL_BOOSTS,
		TUTORIAL_COIN,
		TUTORIAL_TIME_BONUS,
		TUTORIAL_LIGHTNING_MODE,
		TUTORIAL_ZEN_OPTIONS,
		TUTORIAL_GOLD_RUSH,
		TUTORIAL_INFERNO,
		TUTORIAL_POKER_SKULL,
		TUTORIAL_WALLBLAST,
		TUTORIAL_DIG_DARKROCK,
		TUTORIAL_BUTTERFLIES,
		TUTORIAL_POKER,
		TUTORIAL_DISABLED,
		TUTORIAL_ICE_STORM,
		TUTORIAL_CLASSIC,
		TUTORIAL_DIAMOND_MINE,
		TUTORIAL_ZEN_INTRO
	}
}
