using System;

namespace BejeweledLivePlus
{
	public enum UREPLAYPIECE
	{
		UREPLAYPIECE_NORMAL,
		UREPLAYPIECE_FLAME,
		UREPLAYPIECE_STARGEM,
		UREPLAYPIECE_HYPERCUBE,
		UREPLAYPIECE_MULTIPLIER,
		UREPLAYPIECE_COIN,
		UREPLAYPIECE_MYSTERY,
		UREPLAYPIECE_SCRAMBLE,
		UREPLAYPIECE_DETONATE
	}
}
