using System;

namespace BejeweledLivePlus
{
	public enum UREPLAYMATCHFLAG
	{
		UREPLAYMATCHFLAG_FROMUPDATESWAPPING = 1,
		UREPLAYMATCHFLAG_JUSTSWAPPED,
		UREPLAYMATCHFLAG_BULGING = 4,
		UREPLAYMATCHFLAG_FIRING_STARGEM = 8
	}
}
