using System;

namespace BejeweledLivePlus
{
	public enum UREPLAYCMD
	{
		UREPLAYCMD_ADD_GEM,
		UREPLAYCMD_SWAP_GEMS,
		UREPLAYCMD_MATCH_FOUND,
		UREPLAYCMD_ADD_POINTS,
		UREPLAYCMD_DELETE_GEM,
		UREPLAYCMD_FILL_BLANKS,
		UREPLAYCMD_GAME_FLAGS,
		UREPLAYCMD_TIME_LEFT,
		UREPLAYCMD_SPEED_BONUS_UPDATE,
		UREPLAYCMD_BLAZING_SPEED,
		UREPLAYCMD_EXPLODE,
		UREPLAYCMD_SMALL_EXPLODE,
		UREPLAYCMD_SET_VELOCITY,
		UREPLAYCMD_COLLECTED_MULTIPLIER,
		UREPLAYCMD_FIRING_STAR_GEM,
		UREPLAYCMD_FIRING_HYPERCUBE,
		UREPLAYCMD_SHOW_GEM_HINT,
		UREPLAYCMD_GEM_COUNT_POPUP,
		UREPLAYCMD_CASCADE_COUNT_POPUP,
		UREPLAYCMD_MYSTERY_DECIDED,
		UREPLAYCMD_DETONATE,
		UREPLAYCMD_SCRAMBLE
	}
}
