using System;

namespace BejeweledLivePlus.Audio
{
	public enum MUSIC_TYPE
	{
		MUSIC_LOADINGSCREEN,
		MUSIC_MENU,
		MUSIC_CLASSIC,
		MUSIC_CLASSIC_LOSE,
		MUSIC_ZEN,
		MUSIC_BUTTERFLY,
		MUSIC_BUTTERFLY_LOSE,
		MUSIC_POKER,
		MUSIC_POKER_LOSE,
		MUSIC_ICESTORM,
		MUSIC_ICESTORM_LOSE,
		MUSIC_LIGHTNING,
		MUSIC_LIGHTNING_LOSE,
		MUSIC_DIAMOND_MINE,
		MUSIC_DIAMOND_MINE_LOSE,
		MUSIC_TYPE_MAX
	}
}
