using System;

namespace BejeweledLivePlus.Widget
{
	public enum Bej3ButtonType
	{
		BUTTON_TYPE_CUSTOM,
		BUTTON_TYPE_CUSTOM_INV,
		BUTTON_TYPE_BACK,
		BUTTON_TYPE_LONG,
		BUTTON_TYPE_LONG_PURPLE,
		BUTTON_TYPE_LONG_GREEN,
		BUTTON_TYPE_DROPDOWN_UP,
		BUTTON_TYPE_DROPDOWN_DOWN,
		BUTTON_TYPE_DROPDOWN_RIGHT,
		BUTTON_TYPE_INFO,
		BUTTON_TYPE_LEFT_SWIPE,
		BUTTON_TYPE_RIGHT_SWIPE,
		BUTTON_TYPE_PROFILE_PICTURE,
		BUTTON_TYPE_ZEN_SLIDE,
		BUTTON_TYPE_HINT_CAMERA,
		BUTTON_TYPE_HINT_OK,
		TOP_BUTTON_TYPE_NONE,
		TOP_BUTTON_TYPE_MENU,
		TOP_BUTTON_TYPE_CLOSED,
		TOP_BUTTON_TYPE_DISMISS,
		BUTTON_TYPE_GAMECENTER
	}
}
