using System;

namespace BejeweledLivePlus.Widget
{
	public enum TRANSITION_STATE
	{
		TRANSITION_STATE_IDLE,
		TRANSITION_STATE_SLIDE_TO_BOTTOM,
		TRANSITION_STATE_SLIDE_THEN_FADE_IN,
		TRANSITION_STATE_FADE_IN,
		TRANSITION_STATE_FADE_OUT
	}
}
