using System;

namespace BejeweledLIVE
{
	public enum InterfaceStates
	{
		UI_STATE_LOADING,
		UI_STATE_DEMO_SPLASH,
		UI_STATE_MODE_SELECT,
		UI_STATE_INFO,
		UI_STATE_INFO_OVER_GAME,
		UI_STATE_HELP,
		UI_STATE_HELP_OVER_GAME,
		UI_STATE_BLITZ_INTRO,
		UI_STATE_BLITZ_HELP,
		UI_STATE_SCORES,
		UI_STATE_SCORES_OVER_GAME,
		UI_STATE_LEADERBOARD,
		UI_STATE_LEADERBOARD_OVER_GAME,
		UI_STATE_GAME,
		UI_STATE_NAME_ENTRY,
		UI_STATE_GAME_OVER,
		UI_STATE_BLITZ_GAME_OVER,
		UI_STATE_MORE_GAMES,
		UI_STATE_COUNT,
		UI_STATE_UPSELL_SCREEN,
		UI_STATE_THANKS_FOR_BUYING,
		UI_STATE_PLAY_MENU,
		UI_STATE_ACHIEVEMENTS,
		UI_STATE_ACHIEVEMENTS_OVER_GAME,
		UI_STATE_CREDITS,
		UI_STATE_CREDITS_OVER_GAME,
		UI_STATE_SCORES_OVER_GAME_OVER
	}
}
