using System;

namespace BejeweledLIVE
{
	public enum Stats
	{
		STAT_VERSION,
		STAT_FB_USER_ID,
		STAT_WAS_GAME_COMPLETED,
		STAT_SECONDS_PLAYED,
		STAT_POINTS,
		STAT_GEMS_CLEARED,
		STAT_FLAMEGEMS_USED,
		STAT_LASERGEMS_USED,
		STAT_HYPERGEMS_USED,
		STAT_FLAMEGEMS_MADE,
		STAT_LASERGEMS_MADE,
		STAT_HYPERGEMS_MADE,
		STAT_BLAZING_SPEED_EXPLOSION,
		STAT_BIGGESTMATCH,
		STAT_NUM_MOVES,
		STAT_NUM_GOOD_MOVES,
		STAT_NUM_MATCHES,
		STAT_TIME_UP_MULTIPLIER,
		STAT_FINAL_MULTIPLIER,
		STAT_CASCADES,
		STAT_SPEED_POINTS,
		STAT_HIGHEST_SPEED,
		STAT_HURRAH_POINTS,
		STAT_SESSION_ID,
		NUM_STATS
	}
}
