using System;

namespace BejeweledLivePlus.UI
{
	public enum AMBIENCE
	{
		AMBIENCE_MIN,
		AMBIENCE_NONE,
		AMBIENCE_RANDOM,
		AMBIENCE_OCEAN_SURF,
		AMBIENCE_CRICKETS,
		AMBIENCE_RAIN,
		AMBIENCE_WATERFALL,
		AMBIENCE_COASTAL,
		AMBIENCE_FOREST,
		AMBIENCE_MAX,
		MANTRA_MIN,
		MANTRA_NONE,
		MANTRA_GENERAL,
		MANTRA_POSITIVE_THINKING,
		MANTRA_QUIT_BAD_HABITS,
		MANTRA_PROSPERITY,
		MANTRA_SELF_CONFIDENCE,
		MANTRA_WEIGHT_LOSS,
		MANTRA_MAX
	}
}
