using System;

namespace BejeweledLivePlus.UI
{
	public enum ZENOPTIONS_IDS
	{
		EXP_BREATHING_MOD_ID,
		EXP_AMBIENT_SOUND_ID,
		EXP_MANTRAS_ID,
		BTN_BREATHING_MOD_INFO_ID,
		BTN_AMBIENT_SOUND_INFO_ID,
		BTN_MANTRAS_INFO_ID,
		CHK_BREATHING_MOD_VISUAL_INDICATOR_ID,
		SLD_BREATHING_MOD_SPEED_ID,
		SLD_BREATHING_MOD_VOLUME_ID,
		SLD_AMBIENT_SOUND,
		SLD_AMBIENT_VOLUME,
		CHK_MANTRA_SUBLIMINAL,
		SLD_MANTRA_SPEED_VISIBILITY,
		SLD_MANTRA,
		BTN_AMBIENT_LEFT,
		BTN_AMBIENT_RIGHT,
		BTN_MANTRA_LEFT,
		BTN_MANTRA_RIGHT,
		BTN_AMBIENT_SOUND_ID,
		BTN_MANTRAS_ID,
		BTN_BREATH_MOD_ID,
		BTN_BACK_TO_SELECTION_ID,
		BTN_RESUME_ID
	}
}
